/// ROCA vulnerability check and factoring attack.
/// ROCA (Return of Coppersmith's Attack) affects keys generated by certain Infineon chips.
/// Vulnerable keys have n = 65537^a * M' (mod M') for a specific M'.
/// Reference: https://crocs.fi.muni.cz/public/papers/rsa_ccs17

use rug::Integer;
use std::sync::{Arc, atomic::{AtomicBool, Ordering}};
use crate::attack::{RsaAttack, Speed, AttackResult};
use crate::key::{PublicKey, PrivateKey};

pub struct RocaAttack;

// M' values for different key sizes (from roca_attack.py)
fn get_m_prime(key_bits: u32) -> Option<Integer> {
    match key_bits {
        ..=960 => {
            Integer::parse("0x1B3E6C9433A7735FA5FC479FFE4027E13BEA")
                .map(Integer::from).ok()
        }
        992..=1952 => {
            Integer::parse("0x24683144F41188C2B1D6A217F81F12888E4E6513C43F3F60E72AF8BD9728807483425D1E")
                .map(Integer::from).ok()
        }
        1984..=3936 => {
            Integer::parse("0x16928DC3E47B44DAF289A60E80E1FC6BD7648D7EF60D1890F3E0A9455EFE0ABDB7A748131413CEBD2E36A76A355C1B664BE462E115AC330F9C13344F8F3D1034A02C23396E6")
                .map(Integer::from).ok()
        }
        _ => None,
    }
}

/// Check if n is ROCA-vulnerable: n mod M' should be a power of 65537
pub fn is_roca_vulnerable(n: &Integer) -> bool {
    let key_bits = n.significant_bits();
    let m_prime = match get_m_prime(key_bits) {
        Some(m) => m,
        None => return false,
    };
    let base = Integer::from(65537u32);
    let n_mod_m = n.clone().modulo(&m_prime);
    // Check if n_mod_m = 65537^a mod M' for some a
    let mut power = Integer::from(1u32);
    for _ in 0..m_prime.significant_bits() * 2 {
        if power == n_mod_m { return true; }
        power = (power * &base).modulo(&m_prime);
        if power == 1 { break; }
    }
    false
}

impl RsaAttack for RocaAttack {
    fn name(&self) -> &'static str { "roca" }
    fn speed(&self) -> Speed { Speed::Slow }

    fn run(&self, pub_key: &PublicKey, _cipher: &[Vec<u8>], abort: &Arc<AtomicBool>) -> Option<AttackResult> {
        let n = &pub_key.n;
        let e = &pub_key.e;

        if abort.load(Ordering::Relaxed) { return None; }

        if !is_roca_vulnerable(n) {
            log::debug!("[roca] key is not ROCA-vulnerable");
            return None;
        }

        log::info!("[roca] Key is ROCA-vulnerable, attempting Coppersmith factoring...");

        let key_bits = n.significant_bits();
        let m_prime = match get_m_prime(key_bits) {
            Some(m) => m,
            None => return None,
        };

        // Only feasible for 512-bit keys in reasonable time
        if key_bits > 960 {
            log::warn!("[roca] Key size {} bits — ROCA factoring may take very long (hours/days)", key_bits);
            // Still attempt for <=512
            if key_bits > 512 { return None; }
        }

        let base = Integer::from(65537u32);
        // Find a3: n ≡ 65537^a3 (mod M')
        let n_mod_m = n.clone().modulo(&m_prime);
        let mut a3 = 0u64;
        let mut power = Integer::from(1u32);
        let order = m_prime.significant_bits() as u64 * 2;
        for i in 0..order {
            if power == n_mod_m { a3 = i; break; }
            power = (power * &base).modulo(&m_prime);
        }

        // XX = floor(2*sqrt(n) / M')
        let sqrt_n = n.clone().sqrt();
        let xx = Integer::from(2u32) * sqrt_n / &m_prime;
        if xx == 0 { return None; }

        // invmod(M', n)
        let inv_m_n = match m_prime.clone().invert(n) {
            Ok(inv) => inv,
            Err(_) => return None,
        };

        let inf_a = a3 / 2;
        let sup_a = (a3 + order) / 2;

        // Search for the right 'a'
        for a in inf_a..=sup_a.min(inf_a + 50000) {
            if abort.load(Ordering::Relaxed) { return None; }
            // known = 65537^a * M'^-1 mod n
            let base_a = base.clone().pow_mod(&Integer::from(a), &m_prime).ok()?;
            let known = (base_a * &inv_m_n).modulo(n);
            // p = k * M' + 65537^a mod M'
            // We search k such that gcd(k*M' + known, n) > 1
            for k in 0..xx.to_u64().unwrap_or(1000).min(10000) {
                let p_candidate = Integer::from(k) * &m_prime + &known;
                if p_candidate <= 1 || p_candidate >= *n { continue; }
                let g = Integer::from(p_candidate.gcd_ref(n));
                if g > 1 && g < *n {
                    let q = n.clone() / &g;
                    if let Some(pk) = PrivateKey::new(g, q, e.clone(), n.clone()) {
                        return Some(AttackResult { priv_key: Some(pk), decrypted: vec![] });
                    }
                }
            }
        }
        None
    }
}
